import { storage } from "./storage";

const kitData = [
  {
    title: "Golden Abundance Activation",
    description: "Unlock the flow of wealth and prosperity with this powerful frequency vision kit. Combining the 396 Hz Liberation Frequency with theta brainwave entrainment, golden cosmic visuals, and wealth-focused affirmations, this kit is designed to release financial blocks, dissolve scarcity mindset, and align your vibration with unlimited abundance.",
    category: "abundance",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-wealth.png",
    frequencyHz: 396,
    frequencyType: "Solfeggio Liberation + Theta",
    frequencyDescription: "The 396 Hz frequency liberates you from guilt and fear surrounding money. Layered with 6 Hz theta binaural beats, it bypasses the conscious mind's critical filter, allowing abundance affirmations to be absorbed directly by the subconscious.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Radiant Health & Vitality",
    description: "Restore your body's natural healing energy with this rejuvenating frequency vision experience. The 417 Hz Change Frequency works with theta brainwave entrainment to promote cellular renewal, boost your immune system, and cultivate a deep sense of physical vitality at the subconscious level.",
    category: "health",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-health.png",
    frequencyHz: 417,
    frequencyType: "Solfeggio Change + Theta",
    frequencyDescription: "The 417 Hz frequency facilitates change at a cellular level. Combined with theta binaural beats, it cleanses traumatic experiences stored in the body and reprograms the subconscious mind for optimal health.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Divine Love & Connection",
    description: "Open your heart to deep, meaningful love with the 528 Hz Love Frequency. This kit pairs the most powerful healing frequency with theta entrainment and heart-centered affirmations designed to attract your ideal relationship and cultivate unconditional self-love at the deepest subconscious level.",
    category: "love",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-love.png",
    frequencyHz: 528,
    frequencyType: "Solfeggio Love + Theta",
    frequencyDescription: "Known as the 'Love Frequency,' 528 Hz combined with theta binaural beats opens the heart while the subconscious mind absorbs love affirmations without conscious resistance.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Unstoppable Confidence",
    description: "Step into your full power with this confidence-building frequency vision kit. The 639 Hz Connection Frequency combined with theta brainwave entrainment dissolves self-doubt at the subconscious level and builds unshakeable self-worth from within.",
    category: "confidence",
    price: 2997,
    duration: 5,
    thumbnailUrl: "/images/kit-confidence.png",
    frequencyHz: 639,
    frequencyType: "Solfeggio Connection + Theta",
    frequencyDescription: "The 639 Hz frequency enhances your connection to yourself. With theta binaural beats, it reaches the subconscious mind where limiting beliefs about self-worth are stored, replacing them with deep confidence.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Deep Inner Peace",
    description: "Find profound serenity and mental clarity with the 741 Hz Expression Frequency. Theta brainwave entrainment guides your mind into a deeply receptive state while peace affirmations reprogram your subconscious for lasting calm.",
    category: "peace",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-peace.png",
    frequencyHz: 741,
    frequencyType: "Solfeggio Expression + Theta",
    frequencyDescription: "The 741 Hz frequency promotes emotional clarity. Paired with theta binaural beats, it accesses the subconscious mind to dissolve deeply stored anxiety patterns and install lasting inner peace.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Limitless Success & Career",
    description: "Accelerate your career and achieve extraordinary success with the 852 Hz Intuition Frequency. Theta entrainment opens the subconscious gateway while success affirmations reprogram your mind for achievement and excellence.",
    category: "success",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-success.png",
    frequencyHz: 852,
    frequencyType: "Solfeggio Intuition + Theta",
    frequencyDescription: "The 852 Hz frequency awakens intuition and higher consciousness. With theta binaural beats, it programs the subconscious mind for success, removing hidden blocks to achievement.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Total Weight Loss Transformation",
    description: "Transform your relationship with food and your body from the inside out. This kit uses 417 Hz cellular change frequency with theta entrainment to reprogram subconscious eating patterns, body image beliefs, and metabolic programming that have been holding you back.",
    category: "health",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-weight-loss.png",
    frequencyHz: 417,
    frequencyType: "Solfeggio Change + Theta",
    frequencyDescription: "The 417 Hz change frequency paired with theta binaural beats reaches deep into the subconscious where emotional eating patterns, body shame, and self-sabotage programming reside, replacing them with healthy, empowering beliefs.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Public Speaking Mastery",
    description: "Conquer stage fright and become a magnetic speaker by reprogramming the subconscious fear response. The 639 Hz frequency with theta entrainment dissolves deep-rooted public speaking anxiety and installs confidence, clarity, and charisma at the subconscious level.",
    category: "confidence",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-public-speaking.png",
    frequencyHz: 639,
    frequencyType: "Solfeggio Connection + Theta",
    frequencyDescription: "The 639 Hz connection frequency with theta binaural beats bypasses the conscious mind's fear response, allowing new empowering beliefs about communication and presence to take root in the subconscious.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Quit Smoking Forever",
    description: "Break free from nicotine addiction by reprogramming the subconscious triggers that keep you reaching for cigarettes. This kit uses 396 Hz liberation frequency with theta entrainment to release the deep emotional attachments and habitual patterns stored in your subconscious mind.",
    category: "freedom",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-quit-smoking.png",
    frequencyHz: 396,
    frequencyType: "Solfeggio Liberation + Theta",
    frequencyDescription: "The 396 Hz liberation frequency combined with theta binaural beats accesses the subconscious programming that drives smoking addiction, releasing guilt, stress-response triggers, and habitual neural pathways.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Break Free from Gambling",
    description: "Overcome gambling addiction by rewiring the subconscious reward pathways that fuel compulsive betting. Theta entrainment with 396 Hz frequency dissolves the emotional triggers and false beliefs about luck and winning that keep the addiction cycle alive.",
    category: "freedom",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-quit-gambling.png",
    frequencyHz: 396,
    frequencyType: "Solfeggio Liberation + Theta",
    frequencyDescription: "The 396 Hz frequency liberates you from the guilt and fear cycle that fuels gambling addiction. Theta binaural beats ensure the affirmations bypass conscious rationalization and reprogram the subconscious reward system.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Overcome Drug Addiction",
    description: "Reclaim your life from substance dependency by reprogramming the subconscious patterns that drive drug use. The 741 Hz cleansing frequency with theta entrainment detoxifies emotional trauma stored in the subconscious and installs powerful new patterns of freedom and clarity.",
    category: "freedom",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-quit-drugs.png",
    frequencyHz: 741,
    frequencyType: "Solfeggio Cleansing + Theta",
    frequencyDescription: "The 741 Hz frequency cleanses cells and promotes emotional clarity. With theta binaural beats, it penetrates the subconscious mind where addiction patterns are deeply encoded, replacing them with empowering beliefs about sobriety and self-worth.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Alcohol Freedom",
    description: "Break the chains of alcohol dependency by reaching the subconscious programming that drives the urge to drink. This kit combines 741 Hz cleansing frequency with theta entrainment to dissolve emotional triggers, social conditioning, and stress-response patterns linked to alcohol.",
    category: "freedom",
    price: 2997,
    duration: 7,
    thumbnailUrl: "/images/kit-quit-alcohol.png",
    frequencyHz: 741,
    frequencyType: "Solfeggio Cleansing + Theta",
    frequencyDescription: "The 741 Hz cleansing frequency with theta binaural beats accesses the subconscious emotional patterns that drive alcohol dependence, replacing them with feelings of empowerment, clarity, and natural joy.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Sexual Addiction Recovery",
    description: "Heal compulsive sexual behavior by reprogramming the subconscious emotional wounds and attachment patterns that fuel it. The 528 Hz love frequency with theta entrainment restores healthy self-love and emotional balance at the deepest level of the mind.",
    category: "freedom",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-freedom.png",
    frequencyHz: 528,
    frequencyType: "Solfeggio Love + Theta",
    frequencyDescription: "The 528 Hz love frequency paired with theta binaural beats reaches the subconscious attachment wounds and shame that drive compulsive behavior, replacing them with genuine self-love and healthy emotional connections.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Shopping Addiction Release",
    description: "Stop compulsive spending by rewiring the subconscious emotional void that drives impulse buying. This kit uses 396 Hz liberation frequency with theta entrainment to dissolve the emotional triggers and false fulfillment patterns programmed into your subconscious.",
    category: "freedom",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-freedom.png",
    frequencyHz: 396,
    frequencyType: "Solfeggio Liberation + Theta",
    frequencyDescription: "The 396 Hz liberation frequency with theta binaural beats penetrates the subconscious where emotional spending patterns, materialistic programming, and void-filling behaviors reside, replacing them with feelings of wholeness and contentment.",
    featured: false,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Manifest Your Dream Car",
    description: "Program your subconscious mind to attract and manifest your dream vehicle. The 852 Hz intuition frequency with theta entrainment opens your mind to opportunities, aligns your vibration with luxury and success, and removes subconscious blocks to receiving.",
    category: "manifestation",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-dream-car.png",
    frequencyHz: 852,
    frequencyType: "Solfeggio Intuition + Theta",
    frequencyDescription: "The 852 Hz intuition frequency with theta binaural beats opens the subconscious mind to receive abundance. It removes hidden beliefs about what you deserve and programs a clear vision of your dream car into your subconscious reality.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
  {
    title: "Manifest Your Dream Home",
    description: "Imprint the vision of your dream home directly into your subconscious mind. Using 852 Hz intuition frequency with theta brainwave entrainment, this kit dissolves limiting beliefs about homeownership and programs your subconscious to attract your ideal living space.",
    category: "manifestation",
    price: 2997,
    duration: 6,
    thumbnailUrl: "/images/kit-dream-home.png",
    frequencyHz: 852,
    frequencyType: "Solfeggio Intuition + Theta",
    frequencyDescription: "The 852 Hz intuition frequency combined with theta binaural beats programs the subconscious with a vivid blueprint of your dream home, removing hidden blocks around worthiness and opening pathways to manifestation.",
    featured: true,
    stripeProductId: null,
    stripePriceId: null,
  },
];

const affirmationData: Record<string, string[]> = {
  "Golden Abundance Activation": [
    "I am a powerful magnet for wealth and abundance",
    "Money flows to me easily and effortlessly from multiple sources",
    "I am worthy of financial freedom and unlimited prosperity",
    "Every day, in every way, my wealth is increasing",
    "I release all resistance to receiving money and abundance",
    "I am grateful for the wealth that is flowing into my life right now",
    "My income is constantly growing beyond my expectations",
    "I attract lucrative opportunities and financial blessings",
    "Wealth and abundance are my natural birthright",
    "I am open to receiving all the wealth the universe has for me",
    "I am aligned with the energy of financial abundance and success",
    "I attract money naturally and it stays with me permanently",
    "I am financially free and living my most abundant life",
    "My bank accounts overflow with prosperity and wealth",
    "I deserve massive wealth and I accept it graciously now",
    "I release every limiting belief about money from my subconscious",
    "I am a conscious creator of unlimited financial abundance",
    "Prosperity flows to me from expected and unexpected sources",
    "I am grateful for my ever-expanding streams of income",
    "My relationship with money is healthy, positive, and abundant",
    "I vibrate at the frequency of wealth and attract it effortlessly",
    "I am surrounded by abundance in every area of my life",
    "I welcome large sums of money into my life with open arms",
    "My wealth grows exponentially while I sleep peacefully at night",
    "I am worthy of earning more money than I can ever spend",
    "Financial opportunities are drawn to me like a powerful magnet",
    "I transform every challenge into a wealth-building opportunity",
    "I am the master of my financial destiny and I choose abundance",
    "My mind is programmed for prosperity, success, and wealth",
    "I give generously and receive abundantly in perfect balance",
    "I attract wealth-building ideas and act on them with confidence",
    "I am deeply grateful for the abundance flowing through my life",
    "My net worth increases dramatically with each passing month",
    "I am a wise steward of money and it multiplies in my care",
    "I release all fear and guilt surrounding wealth and prosperity",
    "I am living proof that abundance is available to everyone",
    "My subconscious mind is fully programmed for financial success",
    "I attract prosperous people and profitable partnerships naturally",
    "I am abundant, I am wealthy, I am financially free forever",
    "The universe constantly delivers new sources of income to me",
  ],
  "Radiant Health & Vitality": [
    "Every cell in my body vibrates with energy and health",
    "My body is a healing machine and I trust its wisdom",
    "I nourish my body with love, gratitude, and healthy choices",
    "I am getting stronger, healthier, and more vibrant every day",
    "My immune system is powerful and protects me perfectly",
    "I release all illness and disease from my body now",
    "Health and vitality flow through every part of my being",
    "I am grateful for my strong, healthy, and beautiful body",
    "My body heals quickly, naturally, and completely",
    "I choose thoughts that create radiant health and energy",
    "I am overflowing with vibrant energy and perfect health today",
    "My organs function perfectly and harmoniously within my body",
    "I breathe in healing energy and exhale all tension and disease",
    "I am committed to nurturing my body with wholesome nutrition",
    "My sleep is deep and restorative, healing me completely overnight",
    "I radiate health and wellness from the inside out effortlessly",
    "My body regenerates and renews itself at the cellular level",
    "I am in perfect alignment with my body's natural healing wisdom",
    "I choose vitality and my body responds with abundant energy",
    "My blood flows freely, carrying healing nutrients to every cell",
    "I am grateful for my strong bones, muscles, and healthy joints",
    "I attract perfect health through positive thoughts and feelings",
    "My digestive system works perfectly and absorbs all nutrients well",
    "I am worthy of optimal health and I claim it right now",
    "I wake up each morning feeling refreshed, energized, and alive",
    "My heart beats strong and steady, circulating perfect health",
    "I release all stress from my body and embrace deep relaxation",
    "I am youthful, vibrant, and full of radiant life force energy",
    "My body is my temple and I treat it with love and respect",
    "I am free from pain and my body feels wonderful every day",
    "I make choices that support my health and longevity consistently",
    "My nervous system is calm, balanced, and perfectly regulated",
    "I am surrounded by healing energy that nourishes my entire being",
    "I trust my body to maintain perfect balance and optimal health",
    "My mental health is strong, clear, and resilient every single day",
    "I am grateful for the gift of my healthy, functioning body",
    "I attract healing experiences and supportive health practitioners",
    "My body knows exactly how to heal itself and I trust the process",
    "I am a beacon of health, vitality, and radiant well-being",
    "I choose health in every moment and my body rewards me abundantly",
  ],
  "Divine Love & Connection": [
    "I am deeply loved, cherished, and appreciated",
    "I attract loving, supportive, and genuine relationships",
    "My heart is open to giving and receiving unconditional love",
    "I am worthy of deep, passionate, and lasting love",
    "Love flows to me naturally and abundantly from all directions",
    "I radiate love and it returns to me multiplied",
    "I forgive freely and open my heart to new connections",
    "My relationships are filled with joy, trust, and harmony",
    "I am a beautiful soul deserving of extraordinary love",
    "The love I seek is already seeking me",
    "I attract my perfect partner who loves me unconditionally",
    "I am magnetic to deep, soulful, and meaningful connections",
    "I release all past heartbreak and welcome fresh love into my life",
    "I am whole and complete, and love enhances my already beautiful life",
    "I communicate my feelings openly with warmth and vulnerability",
    "I am surrounded by people who genuinely love and support me",
    "I attract relationships that are balanced, healthy, and nurturing",
    "My capacity for love expands infinitely with each passing day",
    "I am lovable exactly as I am without needing to change anything",
    "I create safe spaces for love to grow and flourish naturally",
    "I deserve a partner who sees my beauty inside and out completely",
    "I release the need to control and allow love to flow freely",
    "My heart heals from all past wounds and opens to new love",
    "I am a loving presence and I bring joy to every relationship",
    "I attract kindness, compassion, and tenderness from others naturally",
    "I love myself deeply and this love attracts my ideal partnership",
    "I am open to receiving love in ways I have never experienced before",
    "My romantic relationship is filled with passion, trust, and devotion",
    "I am grateful for the love that surrounds me every single day",
    "I attract soulmates and kindred spirits into my life effortlessly",
    "I am deserving of a love story that exceeds my wildest dreams",
    "I release jealousy and insecurity and embrace trusting love fully",
    "My love life is abundant, exciting, and deeply fulfilling always",
    "I am a source of unconditional love and acceptance for others",
    "I choose to see the best in my partner and nurture our bond",
    "I am emotionally available and ready for deep lasting connection",
    "I attract a relationship built on mutual respect and deep admiration",
    "I am worthy of being loved fiercely and without reservation",
    "I trust the timing of love and know it arrives perfectly for me",
    "I am love incarnate and I share this gift with the world generously",
  ],
  "Unstoppable Confidence": [
    "I believe in myself and my ability to succeed at anything",
    "I am confident, capable, and worthy of greatness",
    "My self-worth is not determined by others' opinions",
    "I step into my power with courage and conviction",
    "I trust myself to make the right decisions for my life",
    "I am enough exactly as I am right now",
    "My confidence grows stronger with every challenge I overcome",
    "I speak my truth with clarity and confidence",
    "I radiate self-assurance and inspire others around me",
    "I am the architect of my life and I build it with confidence",
    "I walk into every room knowing I belong and I matter deeply",
    "I am fearless in pursuing my goals and expressing my ideas",
    "I accept compliments graciously because I know my true worth",
    "I am bold, brave, and brilliant in everything I undertake",
    "I trust my instincts completely and act on them with certainty",
    "I am comfortable being seen, heard, and celebrated by others",
    "I release all self-doubt and embrace my unlimited potential now",
    "I am proud of who I am and who I am becoming each day",
    "I face challenges with unwavering confidence and inner strength",
    "I am magnetic and people are drawn to my authentic confidence",
    "I stand tall and own my space with grace and self-assurance",
    "I am worthy of success and I pursue it without hesitation",
    "I replace every negative thought with empowering self-belief instantly",
    "I am confident in my ability to handle anything life presents me",
    "I celebrate my strengths and accept my imperfections with love",
    "I am unstoppable when I set my mind to achieving a goal",
    "I project confidence naturally because I know my inherent value",
    "I am resilient and I bounce back stronger from every setback",
    "I express my opinions and ideas with conviction and clarity always",
    "I deserve to take up space and share my gifts with the world",
    "I am confident in social situations and connect with others easily",
    "I release comparison and embrace my own unique and powerful journey",
    "I am the definition of inner strength and unshakeable self-belief",
    "I choose courage over comfort and grow stronger every single day",
    "I am worthy of respect and I command it through my presence",
    "I trust the process of life and know I am exactly where I belong",
    "I am a powerful force of positive change in my own life",
    "I embrace uncertainty with confidence knowing I can handle it all",
    "I am deeply secure in who I am at my very core",
    "I radiate unstoppable confidence that empowers everyone around me naturally",
  ],
  "Deep Inner Peace": [
    "I am at peace with myself and the world around me",
    "I release all worry and embrace the present moment",
    "My mind is calm, clear, and centered in stillness",
    "I choose peace over anxiety in every situation",
    "Tranquility flows through me like a gentle river",
    "I let go of what I cannot control and find serenity",
    "Each breath I take fills me with deeper peace and calm",
    "I am safe, I am supported, I am at peace",
    "Inner peace is my natural state and I return to it now",
    "I create a peaceful sanctuary within my own mind and heart",
    "I release all tension from my body and surrender to stillness",
    "I am anchored in calm even when the world moves quickly around me",
    "I choose serenity over chaos and my mind obeys this choice instantly",
    "I am a vessel of tranquility and I radiate calm to others",
    "I forgive everything and everyone and free myself into total peace",
    "I am deeply connected to the infinite peace within my soul",
    "I release the need to rush and allow life to unfold peacefully",
    "I am still and I know that everything is working out perfectly",
    "I inhale peace and exhale all stress, worry, and tension completely",
    "I trust the universe and release all need for anxious control",
    "I am grounded, centered, and balanced in every moment of my life",
    "I allow peaceful thoughts to fill my mind throughout each day",
    "I am free from overthinking and I embrace mental clarity fully",
    "I accept life as it is and find beauty in this present moment",
    "I am surrounded by peace and it permeates every cell of my being",
    "I release all past regrets and future worries right here and now",
    "I am the calm in the center of any storm that surrounds me",
    "I sleep peacefully and wake refreshed with a calm and clear mind",
    "I detach from drama and choose harmony in all my interactions",
    "I am grateful for this moment of pure peace and deep stillness",
    "I radiate calm energy and create peaceful environments wherever I go",
    "I release all emotional turbulence and return to my center of peace",
    "I am at one with the peaceful rhythm of the natural world",
    "I choose gentle thoughts that nurture my soul and calm my spirit",
    "I am free from the burden of worry and I embrace inner serenity",
    "I respond to life with patience, grace, and unwavering inner calm",
    "I am deeply rooted in peace and nothing can disturb my tranquility",
    "I let go of resistance and flow with life in perfect harmony",
    "I find peace in solitude and carry it with me into the world",
    "I am peace, I embody peace, I share peace with all beings",
  ],
  "Limitless Success & Career": [
    "I am destined for extraordinary success and achievement",
    "Every step I take leads me closer to my greatest goals",
    "I am a natural leader who inspires excellence in others",
    "Success is my birthright and I claim it fully today",
    "I attract powerful opportunities that accelerate my career",
    "My work creates massive value and I am rewarded abundantly",
    "I am focused, disciplined, and committed to my vision",
    "I turn obstacles into stepping stones for greater success",
    "My potential is limitless and my future is brilliant",
    "I am recognized and celebrated for my unique contributions",
    "I am a high achiever who consistently exceeds all expectations",
    "I attract mentors and allies who accelerate my professional growth",
    "I am promoted and elevated because of my exceptional work ethic",
    "I create innovative solutions that set me apart in my field",
    "I earn recognition and respect from my colleagues and industry peers",
    "I am magnetic to career opportunities that align with my purpose",
    "I perform at my highest level consistently and with great enthusiasm",
    "I am building a legacy of excellence that inspires future generations",
    "I master new skills quickly and apply them with outstanding results",
    "I am confident in interviews, presentations, and high-stakes situations",
    "I attract abundance through the massive value I deliver every day",
    "I am a visionary leader who turns bold ideas into tangible results",
    "I am respected for my expertise, integrity, and professional excellence",
    "I set ambitious goals and I achieve them with determination and focus",
    "I am always in the right place at the right time for success",
    "I embrace challenges as fuel for my professional growth and advancement",
    "I am compensated generously for the incredible value I bring to others",
    "I operate with a success mindset that attracts winning outcomes consistently",
    "I am a powerful networker who builds meaningful professional relationships",
    "I make decisive choices that propel my career forward with momentum",
    "I am worthy of the highest levels of achievement and professional success",
    "I bring passion and excellence to every project I undertake at work",
    "I am a magnet for promotions, raises, and exciting career advancement",
    "I balance ambition with wisdom and make strategic career decisions effortlessly",
    "I am grateful for my thriving career and the impact I make daily",
    "I attract clients and collaborators who value my skills and expertise deeply",
    "I am a top performer who delivers extraordinary results under any conditions",
    "I lead with authenticity and my leadership inspires others to excel",
    "I am creating the successful career of my dreams right now today",
    "I am destined for greatness and my career reflects my unlimited potential",
  ],
  "Total Weight Loss Transformation": [
    "My body naturally finds and maintains its ideal weight",
    "I love and accept my body as it transforms beautifully",
    "I crave healthy, nourishing foods that fuel my vitality",
    "My metabolism is fast, efficient, and works perfectly for me",
    "I release all emotional attachments to unhealthy eating patterns",
    "I am in complete control of what I eat and how I move",
    "My body burns fat effortlessly and builds lean, strong muscle",
    "I deserve to feel confident, healthy, and vibrant in my body",
    "Every day I am becoming lighter, stronger, and more energized",
    "I release the weight that no longer serves me with love and ease",
    "I listen to my body and eat only when I am truly hungry",
    "I am becoming my ideal body shape with every healthy choice I make",
    "I enjoy exercising and my body responds beautifully to movement",
    "I am free from binge eating and I eat mindfully with intention",
    "I visualize my ideal body and I am becoming that vision right now",
    "I choose water, whole foods, and nourishing meals that heal my body",
    "I release all shame about my body and embrace loving transformation",
    "I am patient with my body as it reaches its perfect weight naturally",
    "I stop eating when I am satisfied and I honor my body's signals",
    "I am reprogramming my subconscious for permanent healthy weight management",
    "I forgive myself for past unhealthy choices and start fresh right now",
    "I am motivated, disciplined, and committed to my weight loss journey completely",
    "I replace comfort eating with healthy coping strategies that serve me better",
    "I am proud of every small step I take toward my ideal weight",
    "I release sugar cravings and my body prefers clean, nutritious fuel",
    "I am transforming from the inside out and my body reflects this change",
    "I choose portion sizes that support my health and ideal body weight",
    "I am grateful for my body's ability to change, heal, and transform",
    "I exercise with joy and my body becomes stronger and leaner daily",
    "I release the identity of being overweight and embrace my new healthy self",
    "I am worthy of having the fit, strong, and vibrant body I desire",
    "I make healthy food choices easily and naturally without feeling deprived",
    "I sleep deeply and my body burns fat efficiently while I rest peacefully",
    "I am breaking free from emotional eating patterns that held me back",
    "I drink plenty of water and my body thrives with proper hydration",
    "I am in harmony with my body and it responds to my healthy intentions",
    "I see myself at my ideal weight and I feel incredible in my body",
    "I have the discipline and willpower to achieve my weight loss goals",
    "I celebrate my body's progress and honor every step of this transformation",
    "I am creating a healthy, lean, and energized body that I absolutely love",
  ],
  "Public Speaking Mastery": [
    "I am a powerful and captivating public speaker",
    "My words flow naturally and effortlessly when I speak",
    "I command attention and respect when I address an audience",
    "I am calm, confident, and collected in front of any crowd",
    "My message is valuable and people are eager to hear me speak",
    "I transform nervous energy into passionate, dynamic delivery",
    "I connect deeply with every audience through authenticity",
    "I speak with clarity, conviction, and magnetic charisma",
    "Every speaking experience makes me stronger and more confident",
    "I am a natural communicator and the world needs my voice",
    "I own the stage and deliver presentations with mastery and grace",
    "I breathe deeply and my voice projects with power and authority",
    "I engage my audience from the first word to the very last",
    "I am articulate and I express complex ideas with simple clarity",
    "I embrace the spotlight and use it to inspire positive change",
    "I am free from stage fright and I perform with total ease",
    "I make eye contact confidently and connect with every individual present",
    "I am a storyteller who captivates hearts and minds effortlessly",
    "I handle unexpected questions with poise, intelligence, and quick thinking",
    "I am comfortable with silence and use pauses for dramatic effect",
    "I inspire action through my words and my authentic passionate delivery",
    "I prepare thoroughly and trust myself to deliver an outstanding presentation",
    "I am praised for my speaking ability and my impact on audiences",
    "I use body language effectively to reinforce my powerful spoken message",
    "I am the kind of speaker people remember long after I finish",
    "I release all fear of judgment and speak from my genuine heart",
    "I turn every presentation into an opportunity to influence and inspire others",
    "I am confident presenting to small groups and massive audiences alike",
    "I enrich my vocabulary daily and communicate with precision and elegance",
    "I am a thought leader whose voice commands respect and attention instantly",
    "I enjoy public speaking and it brings me tremendous joy and fulfillment",
    "I recover gracefully from mistakes and turn them into relatable moments",
    "I am a master at reading the room and adapting my delivery accordingly",
    "I speak with such conviction that my words create lasting positive impact",
    "I am relaxed, present, and fully in the zone when I speak publicly",
    "I visualize successful presentations and my subconscious delivers them flawlessly",
    "I am worthy of sharing my expertise and insights with the world",
    "I use humor naturally to connect with my audience and keep them engaged",
    "I am a confident, charismatic, and compelling speaker in every situation",
    "I close every presentation with power and leave my audience deeply inspired",
  ],
  "Quit Smoking Forever": [
    "I am free from the need for cigarettes and nicotine",
    "My lungs are healing and growing stronger every single day",
    "I choose clean, fresh air over smoke with every breath",
    "I am stronger than any craving and I release it now",
    "My body is cleansing itself of all toxins naturally",
    "I no longer identify as a smoker, I am completely free",
    "I find healthy ways to manage stress and find calm",
    "I love the feeling of being smoke-free and in control",
    "Every day without smoking adds years of vibrant life",
    "I am proud of my decision to quit and I honor it daily",
    "I breathe deeply and my lungs expand with fresh healing air",
    "I am free from nicotine's grip and I celebrate my liberation",
    "I replace the smoking habit with healthy, life-affirming activities daily",
    "I am disgusted by the smell of cigarettes and I choose fresh air",
    "I am rewiring my brain to no longer associate cigarettes with pleasure",
    "I save money every day by being smoke-free and I invest it wisely",
    "I am in control of my habits and I choose health over addiction",
    "I release the social identity of being a smoker completely and forever",
    "I am becoming healthier with every smoke-free hour that passes by",
    "I handle stress with deep breathing, not with harmful cigarette smoke",
    "I am grateful for my improving sense of taste and smell today",
    "I choose life, health, and freedom over the chains of nicotine addiction",
    "I am a non-smoker and this identity grows stronger each day",
    "I release all triggers that once made me reach for a cigarette",
    "I am proud of my willpower and my commitment to a smoke-free life",
    "I respect my body too much to fill it with poisonous cigarette smoke",
    "I am breaking the cycle of addiction for myself and my loved ones",
    "I find natural calm and relaxation without needing any substance at all",
    "I am free and my lungs thank me with every deep, clean breath",
    "I visualize my clean, pink, healthy lungs and I feel truly grateful",
    "I no longer need cigarettes to feel confident, social, or relaxed ever",
    "I am reprogramming my subconscious to permanently reject all nicotine cravings",
    "I enjoy activities more without the constant need to step away and smoke",
    "I am setting a healthy example for everyone who watches my transformation",
    "I wake up each morning grateful for another smoke-free day of freedom",
    "I release all excuses and fully commit to my smoke-free life today",
    "I am stronger than the habit that once controlled my life completely",
    "I embrace the discomfort of change knowing it leads to lasting freedom",
    "I am living proof that anyone can quit smoking permanently with determination",
    "I celebrate my freedom from smoking and I will never go back again",
  ],
  "Break Free from Gambling": [
    "I am free from the compulsion to gamble and bet",
    "I find fulfillment and excitement in healthy activities",
    "My self-worth is not determined by winning or losing",
    "I am in complete control of my finances and decisions",
    "I release the false belief that gambling will solve my problems",
    "I choose financial responsibility and wisdom over risk",
    "I find peace and contentment without the need for the thrill",
    "My happiness comes from within, not from external games of chance",
    "I forgive myself for past gambling and embrace a new chapter",
    "I build my wealth through smart decisions, not through gambling",
    "I am free from the dopamine rush that gambling once provided me",
    "I redirect my competitive energy into productive and rewarding pursuits",
    "I am honest with myself and others about my recovery from gambling",
    "I celebrate every day I resist the urge to gamble as a victory",
    "I am worthy of financial stability and I protect my resources wisely",
    "I release the fantasy of the big win and embrace realistic abundance",
    "I find genuine excitement in building my life through honest hard work",
    "I am surrounded by supportive people who encourage my gambling-free life",
    "I replace gambling time with meaningful activities that nourish my soul deeply",
    "I am breaking the cycle of chasing losses and I accept what is",
    "I am free from the shame and secrecy that gambling brought into my life",
    "I choose to invest my money wisely rather than risk it irresponsibly",
    "I am stronger than the urge to gamble and I prove it daily",
    "I recognize gambling triggers and I respond with healthy coping strategies",
    "I am building a life of integrity, honesty, and financial wisdom now",
    "I release all superstitious beliefs about luck, odds, and winning streaks",
    "I find joy in simple pleasures that cost nothing and mean everything",
    "I am proud of my courage to face my gambling addiction head on",
    "I am reprogramming my reward system to find pleasure in healthy activities",
    "I save the money I once gambled away and watch my wealth grow",
    "I am patient with my recovery and I celebrate every milestone reached",
    "I no longer need the thrill of gambling to feel alive and excited",
    "I am honest about my finances and I manage my money with clarity",
    "I release the power that gambling once held over my life permanently",
    "I am creating a future free from the chaos of compulsive gambling",
    "I choose stability and peace over the rollercoaster of gambling addiction",
    "I am grateful for every day of freedom from gambling's destructive grip",
    "I trust myself with money and I make responsible financial decisions daily",
    "I am healing the root causes that once drove me to gamble compulsively",
    "I am living a life of freedom, purpose, and financial responsibility now",
  ],
  "Overcome Drug Addiction": [
    "I am free from the grip of substance dependency",
    "My mind and body are healing completely every single day",
    "I choose clarity, sobriety, and freedom over numbness",
    "I am stronger than any urge and I release it with love",
    "I deserve a life filled with joy, purpose, and clear thinking",
    "I find healthy ways to process my emotions and pain",
    "Every sober day is a victory I celebrate and honor",
    "I am surrounded by support and love on my recovery journey",
    "I release the shame of my past and step into a bright future",
    "I am worthy of a beautiful, drug-free, and fulfilling life",
    "I am reclaiming my life one clean and sober day at a time",
    "I choose to feel my emotions fully instead of numbing them with substances",
    "I am healing the trauma that once drove me to seek escape",
    "I am proud of my strength and my commitment to recovery today",
    "I release the identity of being an addict and embrace my true self",
    "I find natural highs through exercise, creativity, and human connection",
    "I am rewiring my brain for health, happiness, and lasting sobriety",
    "I forgive myself completely for my past substance use without judgment",
    "I am building a new life that is so fulfilling I never look back",
    "I am worthy of trust and I rebuild it with every sober action",
    "I replace destructive habits with life-affirming practices that serve my highest good",
    "I am surrounded by a recovery community that understands and supports me",
    "I wake up each morning with clarity, purpose, and gratitude for sobriety",
    "I am stronger than any substance and I prove it every single day",
    "I release all shame and embrace my recovery journey with open arms",
    "I am creating new neural pathways that support my sober healthy lifestyle",
    "I choose self-respect over self-destruction with every decision I make today",
    "I am patient and compassionate with myself throughout my healing process",
    "I find peace and contentment in sobriety that drugs could never provide",
    "I am grateful for the second chance at life that recovery gives me",
    "I handle cravings with strength and they pass through me harmlessly always",
    "I am rebuilding my relationships with honesty, integrity, and genuine love",
    "I invest in my health and my future instead of wasting it on substances",
    "I am free from the chains of addiction and I walk in total liberation",
    "I attract positive, sober, and supportive people into my new life daily",
    "I am discovering who I truly am without the mask of substances",
    "I celebrate my sobriety as the greatest achievement of my entire life",
    "I am resilient and every challenge strengthens my commitment to staying clean",
    "I choose freedom over the false comfort that drugs once promised me",
    "I am living proof that recovery is possible and life gets better sober",
  ],
  "Alcohol Freedom": [
    "I am free from the need for alcohol in my life",
    "I enjoy social situations fully without needing to drink",
    "My body is healing and rejuvenating without alcohol",
    "I choose clarity and presence over numbness and escape",
    "I am stronger than any craving and I let it pass through me",
    "I find natural joy and relaxation without alcohol",
    "My relationships are improving as I choose sobriety",
    "I wake up every morning feeling refreshed, clear, and proud",
    "I release all social pressure to drink and honor my choice",
    "I am building a vibrant, healthy, alcohol-free life I love",
    "I am discovering genuine happiness that alcohol could never provide me",
    "I handle social events with ease and confidence without a single drink",
    "I am proud of choosing sobriety and I wear it as my strength",
    "I release the belief that I need alcohol to have fun or relax",
    "I am rewiring my brain to find pleasure in healthy alcohol-free activities",
    "I am free from hangovers, regret, and the shame cycle of drinking",
    "I save money and invest it wisely by choosing an alcohol-free lifestyle",
    "I am present and fully engaged in my life without alcohol's haze",
    "I handle difficult emotions with healthy tools instead of reaching for a drink",
    "I am grateful for my clear mind and my strong, healing liver",
    "I attract friendships based on genuine connection, not shared drinking habits",
    "I release all triggers that once led me to pour that first drink",
    "I am a non-drinker and this identity empowers me more each day",
    "I celebrate milestones and special occasions without needing alcohol to enjoy them",
    "I am sleeping better and my body is thanking me for choosing sobriety",
    "I find that life is more vivid, exciting, and real without alcohol",
    "I am breaking the generational cycle of alcohol dependency in my family",
    "I choose sparkling water, herbal tea, and healthy drinks that nourish me",
    "I am worthy of a clear-headed, vibrant, and fully present life always",
    "I release the romanticized image of alcohol and see it for what it is",
    "I am healing my gut, my brain, and my relationships through sobriety",
    "I handle stress like a champion without needing any chemical assistance at all",
    "I am proud of the courage it takes to live alcohol-free each day",
    "I am discovering new hobbies and passions that fill my life with joy",
    "I am a role model for others who are considering an alcohol-free path",
    "I release all shame about past drinking and focus on my bright future",
    "I am creating memories I will actually remember and cherish forever now",
    "I choose to be fully alive and present for my loved ones always",
    "I am stronger, healthier, and happier without alcohol in my life completely",
    "I celebrate my sobriety as the most empowering decision I have ever made",
  ],
  "Sexual Addiction Recovery": [
    "I am in healthy control of my desires and impulses",
    "I cultivate genuine intimacy and emotional connection",
    "I release compulsive patterns and choose conscious behavior",
    "I am worthy of healthy, balanced, and loving relationships",
    "I find fulfillment through authentic connection, not compulsion",
    "I heal the emotional wounds that drive compulsive behavior",
    "I treat myself and others with dignity and deep respect",
    "My self-worth comes from who I am, not from physical validation",
    "I channel my energy into creativity, growth, and purpose",
    "I am free to experience healthy love and true intimacy",
    "I am reclaiming my power from compulsive sexual behavior permanently",
    "I choose meaningful connection over momentary physical gratification every time",
    "I am healing the shame that fuels my compulsive patterns completely",
    "I am present in my body and I honor its boundaries with respect",
    "I replace compulsive behavior with activities that build my self-esteem daily",
    "I am worthy of a relationship built on trust, respect, and genuine love",
    "I release the need for external validation to feel whole and complete",
    "I am developing emotional intelligence and healthier coping mechanisms each day",
    "I am in control of my choices and I make them consciously now",
    "I forgive myself for past behavior and commit to my healing journey",
    "I am building new neural pathways that support healthy intimate relationships",
    "I find deep satisfaction in emotional closeness and vulnerable authentic connection",
    "I am honest with myself about my triggers and I manage them wisely",
    "I am surrounded by support and understanding on my recovery path forward",
    "I release the secrecy and shame that once controlled my life completely",
    "I choose to be present and mindful in all of my intimate interactions",
    "I am developing a healthy relationship with my own body and desires",
    "I invest my energy in personal growth, career, and meaningful relationships",
    "I am strong enough to sit with uncomfortable feelings without acting out",
    "I am rewriting my story with chapters of healing, growth, and freedom",
    "I attract partners who respect my boundaries and support my well-being fully",
    "I am patient with myself as I learn new patterns of healthy relating",
    "I release all objectification and see others as whole, worthy human beings",
    "I am worthy of deep, lasting love that goes beyond physical attraction only",
    "I am proud of my courage to face this challenge with honesty daily",
    "I fill my life with purpose and passion that transcend compulsive urges",
    "I am healing at the root level and my behavior reflects this transformation",
    "I choose integrity in all my relationships and interactions with others always",
    "I am creating a life where healthy intimacy replaces compulsive behavior completely",
    "I am free from addiction and I embrace healthy, balanced love and connection",
  ],
  "Shopping Addiction Release": [
    "I am free from the compulsion to spend impulsively",
    "I find happiness and fulfillment that money cannot buy",
    "I am enough without material possessions to prove my worth",
    "I choose financial wisdom and intentional spending",
    "I release the emotional void that drives impulse purchases",
    "I find joy in experiences, relationships, and personal growth",
    "My self-worth is not determined by what I own or wear",
    "I am grateful for what I already have and it is enough",
    "I make purchases from a place of intention, not emotion",
    "I am building financial freedom by releasing spending compulsions",
    "I pause before every purchase and ask if it truly serves me",
    "I am rewiring my brain to find satisfaction without buying things",
    "I release the temporary high of shopping and embrace lasting fulfillment",
    "I am worthy of love and acceptance without any new possessions at all",
    "I channel my creative energy into meaningful activities instead of shopping sprees",
    "I am honest about my spending habits and I take full responsibility",
    "I find deep contentment in simplicity and minimalism in my daily life",
    "I release the need to fill emotional voids with material purchases forever",
    "I am saving money and investing in my future instead of impulse buying",
    "I celebrate who I am, not what I own or what brands I wear",
    "I am breaking free from the advertising that manipulates my spending urges",
    "I find genuine excitement in paying off debt and building real savings",
    "I am in control of my spending and I shop with clear intention only",
    "I replace retail therapy with healthy emotional processing and genuine self-care",
    "I am proud of every purchase I choose not to make impulsively today",
    "I release the belief that new things will make me happier inside",
    "I am grateful for my existing possessions and I take care of them",
    "I choose financial security over the fleeting thrill of a new purchase",
    "I am healing the root emotional causes of my compulsive spending patterns",
    "I wait twenty-four hours before making any non-essential purchase decision now",
    "I am building a life rich in experiences, love, and true abundance",
    "I release competition and comparison that drives me to spend beyond my means",
    "I am free from the cycle of buying, guilt, and hiding purchases",
    "I invest in personal development that grows my inner wealth and wisdom",
    "I am discovering that the best things in life truly are free",
    "I make a budget and I honor it with discipline and self-respect daily",
    "I am worthy of financial stability and I protect my resources wisely",
    "I find healthy ways to reward myself that do not involve spending money",
    "I am transforming my relationship with money from compulsive to conscious and free",
    "I am financially empowered and I spend with wisdom, intention, and control",
  ],
  "Manifest Your Dream Car": [
    "I am worthy of driving my dream car and I claim it now",
    "The perfect vehicle is making its way to me right now",
    "I can see myself behind the wheel of my dream car clearly",
    "I attract the financial abundance to afford any car I desire",
    "Luxury and comfort are natural parts of my daily life",
    "I release all limiting beliefs about what I deserve to drive",
    "The universe is conspiring to bring me my perfect vehicle",
    "I feel the excitement and gratitude of owning my dream car",
    "I am aligned with the vibration of automotive luxury and freedom",
    "My dream car is a reflection of my success and I welcome it",
    "I smell the new leather interior of my dream car right now",
    "I hear the powerful engine of my dream vehicle as I drive it",
    "I am magnetizing my dream car into my physical reality effortlessly",
    "I deserve to drive a vehicle that matches my level of success",
    "I am grateful for the incredible car that is manifesting for me",
    "I feel the steering wheel in my hands as I cruise confidently forward",
    "I am worthy of the best and my dream car proves this truth",
    "I release all jealousy toward others and celebrate their luxury vehicles too",
    "I attract the exact make, model, and color of my perfect dream car",
    "I am taking inspired action every day that brings me closer to my car",
    "I can feel the wind through my window as I drive my dream car",
    "I am raising my vibration to match the frequency of luxury and abundance",
    "I visualize parking my dream car in my own driveway every single night",
    "I am creating multiple income streams that support my dream car lifestyle",
    "I deserve to experience the joy and freedom my dream car brings me",
    "I release any guilt about wanting a beautiful, luxurious car for myself",
    "I am manifesting my dream car with faith, gratitude, and focused intention",
    "I see myself receiving the keys to my dream car and I feel overjoyed",
    "I am aligning every thought and action with my dream car manifestation",
    "I attract unexpected opportunities that bring my dream car closer to me",
    "I am confident that my dream car is already mine in the quantum field",
    "I feel the smooth ride and premium comfort of my manifested dream vehicle",
    "I celebrate in advance knowing my dream car is on its way now",
    "I am worthy of experiencing luxury, freedom, and style every time I drive",
    "I program my subconscious mind to attract my dream car naturally and easily",
    "I release all doubt and trust that my dream vehicle is manifesting now",
    "I am surrounded by signs confirming my dream car is coming to me",
    "I take care of my current vehicle while manifesting my upgraded dream car",
    "I am a vibrational match for the luxury car of my deepest desires",
    "I drive my dream car with gratitude, pride, and complete sense of deserving",
  ],
  "Manifest Your Dream Home": [
    "I am worthy of living in my dream home and I claim it now",
    "My perfect home is being prepared for me by the universe",
    "I can see every room of my dream home in vivid detail",
    "I attract the financial abundance to live wherever I choose",
    "I deserve a beautiful, comfortable, and spacious home",
    "I release all limiting beliefs about homeownership and wealth",
    "The doors to my dream home are opening for me right now",
    "I feel the joy and peace of living in my ideal space",
    "My dream home is a reflection of my inner abundance",
    "I am creating the life and home of my wildest dreams",
    "I walk through the front door of my dream home with deep gratitude",
    "I feel the warm sunlight streaming through my dream home's beautiful windows",
    "I am magnetizing my perfect home into my physical reality right now",
    "I deserve a sanctuary that nurtures my soul and inspires my spirit",
    "I am grateful for the dream home that is manifesting for me today",
    "I see myself cooking in my dream kitchen with joy and contentment",
    "I am worthy of spacious rooms, beautiful gardens, and a peaceful environment",
    "I release all fears about mortgages, finances, and homeownership limitations completely",
    "I attract the perfect neighborhood, community, and location for my dream home",
    "I am taking inspired action every day that brings me closer to my home",
    "I can hear the birds singing outside my dream home each morning peacefully",
    "I am raising my vibration to match the frequency of my ideal home",
    "I visualize relaxing in my dream living room surrounded by beauty and comfort",
    "I am creating multiple income streams that support my dream home lifestyle",
    "I deserve to experience the security and joy my dream home brings me",
    "I release any guilt about wanting a beautiful, luxurious home for my family",
    "I am manifesting my dream home with faith, gratitude, and focused intention",
    "I see myself receiving the keys to my dream home and I feel overjoyed",
    "I am aligning every thought and action with my dream home manifestation",
    "I attract unexpected opportunities that bring my dream home closer to me today",
    "I am confident that my dream home is already mine in the quantum field",
    "I feel the comfort and warmth of my beautifully manifested dream home now",
    "I celebrate in advance knowing my dream home is on its way to me",
    "I am worthy of a home filled with love, laughter, and lasting memories",
    "I program my subconscious mind to attract my dream home naturally and easily",
    "I release all doubt and trust that my dream home is manifesting now",
    "I am surrounded by signs confirming my dream home is coming to me",
    "I maintain gratitude for my current space while manifesting my upgraded dream home",
    "I am a vibrational match for the beautiful home of my deepest desires",
    "I live in my dream home with gratitude, peace, and a deep sense of belonging",
  ],
};

const visualData: Record<string, { imageUrl: string; label: string }[]> = {
  abundance: [
    { imageUrl: "/images/visuals/abundance_1_1.jpg", label: "Golden wealth flowing abundantly" },
    { imageUrl: "/images/visuals/abundance_1_2.jpg", label: "Overflowing treasure of prosperity" },
    { imageUrl: "/images/visuals/abundance_1_3.jpg", label: "Radiant golden light of riches" },
    { imageUrl: "/images/visuals/abundance_1_4.jpg", label: "Cosmic abundance energy spiral" },
    { imageUrl: "/images/visuals/abundance_1_5.jpg", label: "Infinite streams of golden prosperity" },
    { imageUrl: "/images/visuals/abundance_1_6.jpg", label: "Lush garden of financial growth" },
    { imageUrl: "/images/visuals/abundance_1_7.jpg", label: "Sparkling diamonds of unlimited wealth" },
    { imageUrl: "/images/visuals/abundance_1_8.jpg", label: "Sunrise over a golden horizon" },
    { imageUrl: "/images/visuals/abundance_1_9.jpg", label: "Majestic waterfall of prosperity" },
    { imageUrl: "/images/visuals/abundance_1_10.jpg", label: "Brilliant golden mandala of wealth" },
  ],
  health: [
    { imageUrl: "/images/visuals/health_1_1.jpg", label: "Vibrant healing green energy" },
    { imageUrl: "/images/visuals/health_1_2.jpg", label: "Cellular renewal light waves" },
    { imageUrl: "/images/visuals/health_1_3.jpg", label: "Peaceful mountain wellness retreat" },
    { imageUrl: "/images/visuals/health_1_4.jpg", label: "Flowing emerald healing waters" },
    { imageUrl: "/images/visuals/health_1_5.jpg", label: "Radiant body vitality glow" },
    { imageUrl: "/images/visuals/health_1_6.jpg", label: "Lush forest of healing energy" },
    { imageUrl: "/images/visuals/health_1_7.jpg", label: "Crystal clear rejuvenation spring" },
    { imageUrl: "/images/visuals/health_1_8.jpg", label: "Sunrise wellness meditation scene" },
    { imageUrl: "/images/visuals/health_1_9.jpg", label: "Blooming flowers of vitality" },
    { imageUrl: "/images/visuals/health_1_10.jpg", label: "Harmonious body energy balance" },
  ],
  love: [
    { imageUrl: "/images/visuals/love_1_1.jpg", label: "Warm rose-gold heart glow" },
    { imageUrl: "/images/visuals/love_1_2.jpg", label: "Cosmic twin flame connection" },
    { imageUrl: "/images/visuals/love_1_3.jpg", label: "Blooming garden of romance" },
    { imageUrl: "/images/visuals/love_1_4.jpg", label: "Soft pink aurora of love" },
    { imageUrl: "/images/visuals/love_1_5.jpg", label: "Radiant heart chakra opening" },
    { imageUrl: "/images/visuals/love_1_6.jpg", label: "Sunset embrace of devotion" },
    { imageUrl: "/images/visuals/love_1_7.jpg", label: "Gentle waves of affection" },
    { imageUrl: "/images/visuals/love_1_8.jpg", label: "Infinite spiral of loving energy" },
    { imageUrl: "/images/visuals/love_1_9.jpg", label: "Cherry blossom path of love" },
    { imageUrl: "/images/visuals/love_1_10.jpg", label: "Sacred union of soulmates" },
  ],
  confidence: [
    { imageUrl: "/images/visuals/confidence_1_1.jpg", label: "Powerful lion spirit rising" },
    { imageUrl: "/images/visuals/confidence_1_2.jpg", label: "Bold mountain summit victory" },
    { imageUrl: "/images/visuals/confidence_1_3.jpg", label: "Radiant purple empowerment aura" },
    { imageUrl: "/images/visuals/confidence_1_4.jpg", label: "Unstoppable warrior of light" },
    { imageUrl: "/images/visuals/confidence_1_5.jpg", label: "Commanding presence energy field" },
    { imageUrl: "/images/visuals/confidence_1_6.jpg", label: "Brilliant crown of self-worth" },
    { imageUrl: "/images/visuals/confidence_1_7.jpg", label: "Soaring eagle of inner strength" },
    { imageUrl: "/images/visuals/confidence_1_8.jpg", label: "Volcanic eruption of personal power" },
    { imageUrl: "/images/visuals/confidence_1_9.jpg", label: "Triumphant sunrise of self-belief" },
    { imageUrl: "/images/visuals/confidence_1_10.jpg", label: "Majestic throne of self-assurance" },
  ],
  peace: [
    { imageUrl: "/images/visuals/peace_1_1.jpg", label: "Serene ocean sunset horizon" },
    { imageUrl: "/images/visuals/peace_1_2.jpg", label: "Tranquil zen garden stillness" },
    { imageUrl: "/images/visuals/peace_1_3.jpg", label: "Calm lake mirror reflection" },
    { imageUrl: "/images/visuals/peace_1_4.jpg", label: "Soft moonlight meditation glow" },
    { imageUrl: "/images/visuals/peace_1_5.jpg", label: "Gentle waterfall of serenity" },
    { imageUrl: "/images/visuals/peace_1_6.jpg", label: "Quiet forest morning mist" },
    { imageUrl: "/images/visuals/peace_1_7.jpg", label: "Floating clouds of tranquility" },
    { imageUrl: "/images/visuals/peace_1_8.jpg", label: "Still waters of inner calm" },
    { imageUrl: "/images/visuals/peace_1_9.jpg", label: "Peaceful lavender field at dusk" },
    { imageUrl: "/images/visuals/peace_1_10.jpg", label: "Sacred temple of deep stillness" },
  ],
  success: [
    { imageUrl: "/images/visuals/success_1_1.jpg", label: "Golden staircase to achievement" },
    { imageUrl: "/images/visuals/success_1_2.jpg", label: "Blazing trail of excellence" },
    { imageUrl: "/images/visuals/success_1_3.jpg", label: "Skyline of limitless potential" },
    { imageUrl: "/images/visuals/success_1_4.jpg", label: "Rocket launch of ambition" },
    { imageUrl: "/images/visuals/success_1_5.jpg", label: "Crown of professional mastery" },
    { imageUrl: "/images/visuals/success_1_6.jpg", label: "Sunrise over empire of success" },
    { imageUrl: "/images/visuals/success_1_7.jpg", label: "Powerful wave of momentum" },
    { imageUrl: "/images/visuals/success_1_8.jpg", label: "Brilliant star of achievement" },
    { imageUrl: "/images/visuals/success_1_9.jpg", label: "Victory peak mountain summit" },
    { imageUrl: "/images/visuals/success_1_10.jpg", label: "Shining pathway to greatness" },
  ],
  freedom: [
    { imageUrl: "/images/visuals/freedom_1_1.jpg", label: "Broken chains of liberation" },
    { imageUrl: "/images/visuals/freedom_1_2.jpg", label: "Open sky of boundless freedom" },
    { imageUrl: "/images/visuals/freedom_1_3.jpg", label: "Soaring bird above the clouds" },
    { imageUrl: "/images/visuals/freedom_1_4.jpg", label: "Butterfly emerging from cocoon" },
    { imageUrl: "/images/visuals/freedom_1_5.jpg", label: "Wide open road to recovery" },
    { imageUrl: "/images/visuals/freedom_1_6.jpg", label: "Rising phoenix of transformation" },
    { imageUrl: "/images/visuals/freedom_1_7.jpg", label: "Clear horizon of new beginnings" },
    { imageUrl: "/images/visuals/freedom_1_8.jpg", label: "Bright dawn of liberation" },
    { imageUrl: "/images/visuals/freedom_1_9.jpg", label: "Flowing river of release and renewal" },
    { imageUrl: "/images/visuals/freedom_1_10.jpg", label: "Radiant light of total freedom" },
  ],
  manifestation: [
    { imageUrl: "/images/visuals/manifestation_1_1.jpg", label: "Cosmic portal of creation" },
    { imageUrl: "/images/visuals/manifestation_1_2.jpg", label: "Swirling galaxy of infinite possibility" },
    { imageUrl: "/images/visuals/manifestation_1_3.jpg", label: "Crystal vision board of dreams" },
    { imageUrl: "/images/visuals/manifestation_1_4.jpg", label: "Starlit path to your desires" },
    { imageUrl: "/images/visuals/manifestation_1_5.jpg", label: "Magnetic vortex of attraction" },
    { imageUrl: "/images/visuals/manifestation_1_6.jpg", label: "Quantum field of pure potential" },
    { imageUrl: "/images/visuals/manifestation_1_7.jpg", label: "Brilliant nebula of dreams realized" },
    { imageUrl: "/images/visuals/manifestation_1_8.jpg", label: "Sacred geometry of manifestation" },
    { imageUrl: "/images/visuals/manifestation_1_9.jpg", label: "Aurora of dreams coming true" },
    { imageUrl: "/images/visuals/manifestation_1_10.jpg", label: "Infinite universe of possibilities" },
  ],
};

export async function seedDatabase() {
  const kitCount = await storage.getKitCount();
  if (kitCount < kitData.length) {
    if (kitCount > 0) {
      console.log("Reseeding database with expanded kit catalog...");
      await storage.clearAllKitsAndAffirmations();
    }

    console.log("Seeding kits and affirmations...");
    for (const kit of kitData) {
      const createdKit = await storage.createKit(kit);
      const affs = affirmationData[kit.title] || [];
      for (let i = 0; i < affs.length; i++) {
        await storage.createAffirmation({
          kitId: createdKit.id,
          text: affs[i],
          orderIndex: i,
          displayDuration: 25,
          visualType: "fade",
        });
      }
      console.log(`  Seeded kit: ${kit.title} with ${affs.length} affirmations`);
    }
  } else {
    const affirmationCount = await storage.getAffirmationCount();
    if (affirmationCount < 640) {
      console.log(`Kits exist but only ${affirmationCount} affirmations found (need 640). Reseeding all...`);
      await storage.clearAllKitsAndAffirmations();

      for (const kit of kitData) {
        const createdKit = await storage.createKit(kit);
        const affs = affirmationData[kit.title] || [];
        for (let i = 0; i < affs.length; i++) {
          await storage.createAffirmation({
            kitId: createdKit.id,
            text: affs[i],
            orderIndex: i,
            displayDuration: 25,
            visualType: "fade",
          });
        }
        console.log(`  Seeded kit: ${kit.title} with ${affs.length} affirmations`);
      }
    } else {
      console.log(`Database already seeded with ${kitCount} kits and ${affirmationCount} affirmations.`);
    }
  }

  const visualCount = await storage.getVisualCount();
  if (visualCount < 80) {
    if (visualCount > 0) {
      console.log("Reseeding visuals...");
      await storage.clearAllVisuals();
    }

    console.log("Seeding visual data...");
    for (const [category, visuals] of Object.entries(visualData)) {
      for (const visual of visuals) {
        await storage.createVisual({
          category,
          imageUrl: visual.imageUrl,
          label: visual.label,
        });
      }
      console.log(`  Seeded ${visuals.length} visuals for category: ${category}`);
    }
  } else {
    console.log(`Visuals already seeded (${visualCount} visuals found).`);
  }

  const visionBoardCount = await storage.getVisionBoardImageCount();
  if (visionBoardCount < 800) {
    if (visionBoardCount > 0) {
      console.log("Reseeding vision board images...");
      await storage.clearAllVisionBoardImages();
    }

    console.log("Seeding vision board images...");
    const { visionBoardData } = await import("./seed-vision-board");
    const allKits = await storage.getAllKits();

    for (const kit of allKits) {
      const entries = visionBoardData[kit.title];
      if (entries) {
        for (let i = 0; i < entries.length; i++) {
          await storage.createVisionBoardImage({
            kitId: kit.id,
            imageUrl: entries[i].imageUrl,
            label: entries[i].label,
            orderIndex: i,
          });
        }
        console.log(`  Seeded ${entries.length} vision board images for: ${kit.title}`);
      }
    }
  } else {
    console.log(`Vision board images already seeded (${visionBoardCount} images found).`);
  }

  console.log("Database seeding complete!");
}
